// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStoreInventoryManagement.Core.EF.Context;

namespace SmartStoreInventoryManagement.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200506023834_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategorNumber")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("OfficeNo")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("TelNo")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b6b6b0-0825-4975-a93d-df3dc86f8cc7"),
                            ConcurrencyStamp = "236b682f3a444788aa7f8b4d4de8ef37",
                            Name = "SYS_ADMIN",
                            NormalizedName = "SYS_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0718ddef-4067-4f29-aaa1-98c1548c1807"),
                            ConcurrencyStamp = "97dd81f0508145a9981b25c741ae482f",
                            Name = "SUPER_ADMIN",
                            NormalizedName = "SUPER_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("8b93d395-a71a-4620-9352-5b9e6b3b6045"),
                            ConcurrencyStamp = "bb68078c46e04a94b2f95d4da7994d0c",
                            Name = "SUPERUSER",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = new Guid("02bde570-4aa8-4c60-a462-07154aa69520"),
                            ConcurrencyStamp = "c0fb1a26e17947cb8c77a027365b204e",
                            Name = "STAFF_USER",
                            NormalizedName = "STAFF_USER"
                        });
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUseApplication")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SystemUser")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            AccessFailedCount = 0,
                            Activated = true,
                            CanUseApplication = false,
                            ConcurrencyStamp = "3e756485-c7db-4288-bf36-73888944b33c",
                            CreatedOnUtc = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "system@smartstore.com",
                            EmailConfirmed = true,
                            FirstName = "Olaleye",
                            Gender = 0,
                            IsDeleted = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLoginDate = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walure",
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSTEM@SMARTSTORE.COM",
                            NormalizedUserName = "SYSTEM@SMARTSTORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPCUvYFU6L6CNxkpfAkIrg77O86IQUdn0Vsg/lt6EPAHJqdtm8v+FgaBnw6WJKbnyg==",
                            PhoneNumber = "08067623699",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "99ae0c45-d682-4542-9ba7-1281e471916b",
                            SystemUser = false,
                            TwoFactorEnabled = false,
                            UserName = "system@smartstore.com",
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba"),
                            AccessFailedCount = 0,
                            Activated = true,
                            CanUseApplication = false,
                            ConcurrencyStamp = "271ca2bf-9ee7-458f-9f46-43e57bce4a7b",
                            CreatedOnUtc = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@smartstore.com",
                            EmailConfirmed = true,
                            FirstName = "Olaleye",
                            Gender = 0,
                            IsDeleted = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLoginDate = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walure",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SMARTSTORE.COM",
                            NormalizedUserName = "SUPERADMIN@SMARTSTORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEh8MTEG+psrvl1bZ1zsFiedP5o61tTKghBfsUnb4kwuwI8VvI0A56IrttVGVCLGTA==",
                            PhoneNumber = "08067623699",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "016020e3-5c50-40b4-9e66-bba56c9f5bf2",
                            SystemUser = false,
                            TwoFactorEnabled = false,
                            UserName = "superadmin@smartstore.com",
                            UserType = 1
                        },
                        new
                        {
                            Id = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a"),
                            AccessFailedCount = 0,
                            Activated = true,
                            CanUseApplication = false,
                            ConcurrencyStamp = "43db738c-a0f2-462c-b998-2716fc04e348",
                            CreatedOnUtc = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "storemanager@vericore.com",
                            EmailConfirmed = true,
                            FirstName = "Prolifik",
                            Gender = 0,
                            IsDeleted = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLoginDate = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lexzy",
                            LockoutEnabled = false,
                            NormalizedEmail = "STOREMANAGER@VERICORE.COM",
                            NormalizedUserName = "STOREMANAGER@VERICORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEhCB0MAR31LnATGRM0QsgteAyGn/VKq6CJNNNI+mJPLhselT3V/Z2QvZk0SfyOLBQ==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7d728c76-1c51-491a-99db-bde6a5b0655b",
                            SystemUser = false,
                            TwoFactorEnabled = false,
                            UserName = "storemanager@vericore.com",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("129712e3-9214-4dd3-9c03-cfc4eb9ba979"),
                            AccessFailedCount = 0,
                            Activated = true,
                            CanUseApplication = false,
                            ConcurrencyStamp = "8fc81bbc-16b6-4455-b8bf-e52dfd9c3709",
                            CreatedOnUtc = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@smartstore.com",
                            EmailConfirmed = true,
                            FirstName = "Bolaji",
                            Gender = 0,
                            IsDeleted = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLoginDate = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Siraj",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@SMARTSTORE.COM",
                            NormalizedUserName = "STAFF@SMARTSTORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHSdHo6UH+3EIuEaxyw3X4d7ca2+F//Eo7SNQ0xBi1ERzZSGl8b+UtbdjO5Puv4AgQ==",
                            PhoneNumber = "08062066851",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "953d3fd1-99e3-4fe7-a20d-3598baa96099",
                            SystemUser = false,
                            TwoFactorEnabled = false,
                            UserName = "staff@smartstore.com",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            RoleId = new Guid("a1b6b6b0-0825-4975-a93d-df3dc86f8cc7"),
                            Id = 0
                        },
                        new
                        {
                            UserId = new Guid("3fb897c8-c25d-4328-9813-cb1544369fba"),
                            RoleId = new Guid("0718ddef-4067-4f29-aaa1-98c1548c1807"),
                            Id = 0
                        },
                        new
                        {
                            UserId = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a"),
                            RoleId = new Guid("8b93d395-a71a-4620-9352-5b9e6b3b6045"),
                            Id = 0
                        },
                        new
                        {
                            UserId = new Guid("129712e3-9214-4dd3-9c03-cfc4eb9ba979"),
                            RoleId = new Guid("02bde570-4aa8-4c60-a462-07154aa69520"),
                            Id = 0
                        });
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Category_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("OpenBalance")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductLocation_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductShelf_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RFID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForInactivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("StockOutWarning")
                        .HasColumnType("bit");

                    b.Property<string>("TagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitOfMeasure_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productType")
                        .HasColumnType("int");

                    b.Property<int>("productstatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("ProductLocation_Id");

                    b.HasIndex("ProductShelf_Id");

                    b.HasIndex("UnitOfMeasure_Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.ProductLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductLocation");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.ProductShelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductShelf");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNo")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Staff_Type")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f1c57d1-14d9-4aca-8457-543b5874568b"),
                            CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            CreatedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifiedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            ModifiedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            StaffNo = "0001",
                            Staff_Type = 0,
                            Status = false,
                            Title = "Mrs.",
                            User_Id = new Guid("973af7a9-7f18-4e8b-acd3-bc906580561a")
                        },
                        new
                        {
                            Id = new Guid("dbb5809d-b496-45c0-a3f3-db2ac9e84251"),
                            CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            CreatedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifiedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            ModifiedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            StaffNo = "0002",
                            Staff_Type = 0,
                            Status = false,
                            Title = "Mr",
                            User_Id = new Guid("129712e3-9214-4dd3-9c03-cfc4eb9ba979")
                        },
                        new
                        {
                            Id = new Guid("8270691f-b40e-4794-8960-6b6b7ddc8e2c"),
                            CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            CreatedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifiedBy = new Guid("1989883f-4f99-43bf-a754-239bbbfec00e"),
                            ModifiedOn = new DateTime(2019, 9, 17, 6, 54, 57, 860, DateTimeKind.Utc),
                            StaffNo = "0003",
                            Staff_Type = 0,
                            Status = false,
                            Title = "Mr",
                            User_Id = new Guid("129712e3-9214-4dd3-9c03-cfc4eb9ba979")
                        });
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decimals")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("Company_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MyAppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MyAppUser_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeNumber")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Company_Id");

                    b.HasIndex("MyAppUserId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppRoleClaim", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserClaim", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserLogin", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserRole", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.MyAppUserToken", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Product", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id");

                    b.HasOne("SmartStoreInventoryManagement.Core.Models.ProductLocation", "ProductLocation")
                        .WithMany()
                        .HasForeignKey("ProductLocation_Id");

                    b.HasOne("SmartStoreInventoryManagement.Core.Models.ProductShelf", "ProductShelf")
                        .WithMany()
                        .HasForeignKey("ProductShelf_Id");

                    b.HasOne("SmartStoreInventoryManagement.Core.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasure_Id");
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Staff", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartStoreInventoryManagement.Core.Models.Vendor", b =>
                {
                    b.HasOne("SmartStoreInventoryManagement.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStoreInventoryManagement.Core.Models.MyAppUser", "MyAppUser")
                        .WithMany()
                        .HasForeignKey("MyAppUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
